services:
  backend:
    build: .
    container_name: futuro_ia_backend
    ports:
      - "8000:8000"
    env_file: .env  # Carga tus variables de AWS y Bedrock
    volumes:
      - .:/app      # Permite ver cambios en el c√≥digo sin reconstruir

  frontend:
    image: python:3.11-slim
    container_name: futuro_ia_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./web:/web
    working_dir: /web
    # Forzamos a que sirva el contenido de /web en el puerto 3000
    command: python -m http.server 3000 --bind 0.0.0.0